### ISSUE TITLE
API Corrections

### ISSUE THREAD

**Issue by abhishektyagi-zoom** [tekina/fuel_prices_india#1]
url: http://fuelpriceindia.herokuapp.com

Fetch available cities list:

GET /main/city_list
```
Change this to 
GET /main/cities
```

Returns a list of cities for which fuel prices are available

response: { cities: ["Bengaluru", Pune, Mumbai, ..., Nagpur] }

Fetch fuel price for a city:

POST /main/fetch_fuel_price
```
this to 
GET /main/city/{cityname/id}/fuel_type/{type}
```

payload: { city: {city_name}, fuelType: {fuelType} }

a. city_name can be any city from the list obtained in the GET city_list API call.

b. fuelType: Petrol or Diesel

sample payload: { city: "Mumbai" , fuelType: Petrol }

response: { city: {city_name}, price: {fuel_price} }

**Comment by Nitin-jha2016** [comment]
Why its not cover all cities in India?

**Comment by bridgecodes** [comment]
Dear @Nitin-jha2016 Fuel Price remain same per state of India so the author keeping state capital as city.

**Comment by iamrahulkohli** [comment]
Is this working fine? I am not able to Test the endpoints

**Comment by tekina** [comment]
@Nitin-jha2016 what @bridgecodes said is correct. 
However, if there is a city which you feel is missing, you can create a separate issue and I'll add it if possible.

**Comment by pkc456** [comment]
@tekina : Add Punjab and Himachal Pradesh in the list please.
