### ISSUE TITLE
Very good API, More major cities should be added...

### ISSUE THREAD

**Issue by arjeriaharsh** [tekina/fuel_prices_india#4]
This api is very good, just waiting for more major cities in the list. Cities like Agra, Gwalior, Jabalpur, Kanpur, Varanasi, etc should be there.

**Comment by tekina** [comment]
Hi @arjeriaharsh, I'm planning to move to data provided by Indian Oil for all state capitals, which will be reliable. Can add cities other than those depending on a reliable source.

**Comment by tekina** [comment]
I've moved the source to Indian Oil. Data for all state capitals is now available.

**Comment by pkc456** [comment]
@tekina :  Data for some states like Punjab, Himachal Pradesh is still missing. Please add all the states.
