### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by gauravarora011** [tekina/fuel_prices_india#5]
What is your source of data ?

**Comment by KishoreBabuIN** [comment]
Hi @tekina , I see a difference in the prices mentioned on the Indian Oil website vs the price returned by the API. 

This is for Chennai, and June 27, 2017 btw.

So what is the source of your prices? Kudos for the api though anyway. I hope to build something on top of this.

<img width="610" alt="screen shot 2017-06-27 at 10 44 13 am" src="https://user-images.githubusercontent.com/1313194/27571901-5a6d404c-5b26-11e7-9cdf-4ab7562194d1.png">
<img width="682" alt="screen shot 2017-06-27 at 10 40 41 am" src="https://user-images.githubusercontent.com/1313194/27571902-5a6fe1d0-5b26-11e7-9778-5c13484f4196.png">

**Comment by bsidio** [comment]
is it due to caching?

**Comment by tekina** [comment]
@gauravarora011 I have moved the source to [Indian Oil](iocl.com)
@barykaed This issue should be rectified now.
@bsidio yes, that is correct. I was caching the price for 24 hours, regardless of the current time. Now the cache should expire at midnight.

**Comment by gauravarora011** [comment]
The prices don't change overnight, they are updated at 6am.

**Comment by tekina** [comment]
Corrected it, for now prices will refresh at 5:30 am daily. Will update it to 6 am once I can speed up fetching the webpage.
