### ISSUE TITLE
Suggestion: Response structure

### ISSUE THREAD

**Issue by rikithakkar1012** [tekina/fuel_prices_india#7]
is it possible to make the response key same every day? As yesterday `GET /price?city={city_name}&fuel_type={fuel_type}` was giving `Petrol` in response and today it is giving `petrol`. So every time developer has to change Model class in while calling web service through retrofit.

**Comment by tekina** [comment]
Hey @rikithakkar1012, this was a one time change since I was porting the source to an official source (IOCL). Such changes will not happen from now on.

**Comment by rikithakkar1012** [comment]
thanks a lot. the structure which is showing currently is final?
